trigger:
  branches:
    include: ["test", "main"]

variables: 
- group: 'environmental_variables'

jobs:
- job: Publish All Items
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: pip install fabric-cicd
    displayName: 'Install  fabric-cicd'

  - task: PythonScript@0  
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'src/publish_all_items.py' 
      workingDirectory: '$(Build.SourcesDirectory)/src'
      failOnStderr: true  
    env:
      FABRIC_CLIENT_ID: $(FABRIC_CLIENT_ID)
      FABRIC_CLIENT_SECRET: $(FABRIC_CLIENT_SECRET)
      FABRIC_TENANT_ID: $(FABRIC_TENANT_ID)
      SERVICE_PRINCIPAL_OBJECT_ID: $(SERVICE_PRINCIPAL_OBJECT_ID)
      ADMIN_USER_ID: $(ADMIN_USER_ID)
      FABRIC_CAPACITY_ID: $(FABRIC_CAPACITY_ID)

      BRANCH_NAME: 'WTF'