name: Create prod release build
run-name: Create [prod] release build from branch ${{ github.ref_name }} 

on:
    workflow_dispatch:

jobs:
    deployment-job:
      name: Create Feature Workspace
      runs-on: ubuntu-latest

      steps:
        - name: Check out the code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"

        - name: Install Python SDK for Fabric REST APIs
          run: |
              pip install microsoft-fabric-api -q

        - name: Install  fabric-cicd
          run: |
              pip install fabric-cicd -q

        - name: Install PyNaCl
          run: |
                pip install PyNaCl -q

        - name: Create [prod] release build
          env:
              BRANCH_NAME: ${{ github.ref_name }}
              GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
              GITHUB_WORKSPACE : $GITHUB_WORKSPACE
              AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
              AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
              AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
              PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
              ORGANIZATION_GITHUB: ${{ vars.ORGANIZATION_GITHUB }}
              FABRIC_CAPACITY_ID: ${{ vars.FABRIC_CAPACITY_ID }}         
              ADMIN_USER_ID: ${{ vars.ADMIN_USER_ID }}
              WORKSPACE_ID_DEV: ${{ vars.WORKSPACE_ID_DEV }}
              WORKSPACE_ID_TEST: ${{ vars.WORKSPACE_ID_TEST }}
              WORKSPACE_ID_PROD: ${{ vars.WORKSPACE_ID_PROD }}
              FEATURE_NAME: ${{ inputs.feature_name }}
          run: 
              python 'src/create_prod_release_build.py'
