table Sales
	lineageTag: a4637a45-cb0b-4bce-b75b-13e1a5efae06

	measure 'Sales Revenue' = Sum(Sales[Sales])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales Metrics
		lineageTag: 5ea1636a-303f-44db-b500-622529d0749d

	measure 'Customer Count' = DISTINCTCOUNT(Sales[CustomerId])
		formatString: #,0
		displayFolder: Sales Metrics
		lineageTag: 94141404-6d60-41fe-a767-7af9150d25b2

	measure 'First Sale' = FIRSTDATE(Sales[Date])
		formatString: mmm d, yyyy
		displayFolder: Date Metrics
		lineageTag: 57b47456-57b9-4248-9600-2497e60f375c

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Last Sale' = LASTDATE(Sales[Date])
		formatString: mmm d, yyyy
		displayFolder: Date Metrics
		lineageTag: d1101050-6e52-453f-87df-58bdcb744a13

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Units Sold' = SUM(Sales[Quantity])
		formatString: #,0
		displayFolder: Sales Metrics
		lineageTag: 5e914420-dc4c-4a47-b376-6fd6ade30050

	measure 'Customer Rank' = ```
			
			IF( 
			    HASONEVALUE(Customers[Customer]), 
			    RANKX( 
			    ALLSELECTED(Customers), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: 2f823a25-58db-4640-bc89-c14c94552f4b

	measure 'Product Rank' = ```
			
			IF( 
			    HASONEVALUE(Products[Product]), 
			    RANKX( 
			    ALLSELECTED(Products), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: cc3f8a68-da6d-4f12-9b75-9d12af58fedf

	measure 'City Rank' = ```
			
			IF( 
			    HASONEVALUE(Customers[City]), 
			    RANKX( 
			    ALLSELECTED(Customers[City]), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: ec44490e-46ee-472a-9223-b165f7702334

	column Id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 41ccda35-54a1-4c9a-9a16-d0b668d47aaa
		summarizeBy: count
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 182c44ce-d0cc-4596-a2ea-f2548e808563
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c08ca3be-4cd0-424e-b619-700a25581616
		summarizeBy: sum
		sourceColumn: Sales

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ed4a661a-1e62-439e-9d4d-d055107aebb9
		summarizeBy: none
		sourceColumn: ProductId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: mmm d, yyyy
		lineageTag: 4c997cd4-bf06-4811-bc52-ab9711bf6bea
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee58ddcd-e127-4697-82fb-cf2b3e6f978a
		summarizeBy: none
		sourceColumn: CustomerId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		queryGroup: model
		source = ```
				let
				    Source = GetCsvFilesFromAzure,
				    CsvBinary = Source{[#"Folder Path"=AZURE_STORAGE_ROOT, Name="InvoiceDetails.csv"]}[Content],
				    ImportedCsv = Csv.Document(CsvBinary, [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    PromotedHeaders = Table.PromoteHeaders(ImportedCsv, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(PromotedHeaders,{{"Id", Int64.Type}, {"SalesAmount", type number}, {"InvoiceId", Int64.Type}, {"ProductId", Int64.Type}}),
				    MergedQueries = Table.NestedJoin(#"Changed Type", {"InvoiceId"}, Invoices, {"InvoiceId"}, "Invoices", JoinKind.LeftOuter),
				    ExpandedInvoices = Table.ExpandTableColumn(MergedQueries, "Invoices", {"Date", "CustomerId"}, {"Date", "CustomerId"}),
				    RemovedColumns = Table.RemoveColumns(ExpandedInvoices,{"InvoiceId"}),
				    RenamedColumns = Table.RenameColumns(RemovedColumns,{{"SalesAmount", "Sales"}}),
				    ChangedType = Table.TransformColumnTypes(RenamedColumns,{{"Id", Int64.Type}, {"ProductId", Int64.Type}, {"Quantity", Int64.Type}, {"Sales", Currency.Type}, {"Date", type date}}),
				    #"Sorted Rows" = Table.Sort(ChangedType,{{"Date", Order.Descending}})
				in 
				    #"Sorted Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

