trigger: none

variables: 
- group: 'environmental_variables'

jobs:
- job: apply_post_deploy_updates_to_prod
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: pip install microsoft-fabric-api -q
    displayName: 'Install Python SDK for Fabric REST APIs'
  
  - script: pip install fabric-cicd -q
    displayName: 'Install  fabric-cicd'

  - task: PythonScript@0  
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'src/apply_post_deploy_updates_to_prod.py' 
      workingDirectory: '$(Build.SourcesDirectory)/src'
      failOnStderr: false  
    env:
      BRANCH_NAME: $(Build.SourceBranchName)
      SOURCES_DIRECTORY: $(Build.SourcesDirectory)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)
      SERVICE_PRINCIPAL_OBJECT_ID: $(SERVICE_PRINCIPAL_OBJECT_ID)
      AZURE_STORAGE_SAS_TOKEN: $(AZURE_STORAGE_SAS_TOKEN)
      ADMIN_USER_ID: $(ADMIN_USER_ID)
      FABRIC_CAPACITY_ID: $(FABRIC_CAPACITY_ID)
      WORKSPACE_ID_DEV: $(WORKSPACE_ID_DEV)
      WORKSPACE_ID_TEST: $(WORKSPACE_ID_TEST)
      WORKSPACE_ID_PROD: $(WORKSPACE_ID_PROD)
