trigger:
  branches:
    include:
      - main
      - dev

variables: 
- group: 'environmental_variables'

jobs:
- job: Sync_Workspace
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true

  - script: pip install msal -q
    displayName: 'Install msal'

  - task: PythonScript@0  
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'src/sync_workspace.py' 
      workingDirectory: '$(Build.SourcesDirectory)/src' # Optional: Specify the working directory for the script
      failOnStderr: true # Optional: Fail the task if any text is written to the stderr stream  
    env:
      FABRIC_CLIENT_ID: $(FABRIC_CLIENT_ID)
      FABRIC_CLIENT_SECRET: $(FABRIC_CLIENT_SECRET)
      FABRIC_TENANT_ID: $(FABRIC_TENANT_ID)
      SERVICE_PRINCIPAL_OBJECT_ID: $(SERVICE_PRINCIPAL_OBJECT_ID)
      ADMIN_USER_ID: $(ADMIN_USER_ID)
      DEVELOPERS_GROUP_ID: $(DEVELOPERS_GROUP_ID)
      FABRIC_CAPACITY_ID: $(FABRIC_CAPACITY_ID)
      DEV_WORKSPACE_ID: $(DEV_WORKSPACE_ID)
      PROD_WORKSPACE_ID: $(PROD_WORKSPACE_ID)
