table Sales
	lineageTag: d886d6ae-6f5a-4c3c-b518-26ded0347520

	measure 'Sales Revenue' = Sum(Sales[Sales])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales Metrics
		lineageTag: 5ea1636a-303f-44db-b500-622529d0749d

	measure 'Customer Count' = DISTINCTCOUNT(Sales[CustomerId])
		formatString: #,0
		displayFolder: Sales Metrics
		lineageTag: 94141404-6d60-41fe-a767-7af9150d25b2

	measure 'First Sale' = FIRSTDATE(Sales[Date])
		formatString: m/d/yyyy
		displayFolder: Date Metrics
		lineageTag: 57b47456-57b9-4248-9600-2497e60f375c

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Last Sale' = LASTDATE(Sales[Date])
		formatString: m/d/yyyy
		displayFolder: Date Metrics
		lineageTag: d1101050-6e52-453f-87df-58bdcb744a13

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Units Sold' = SUM(Sales[Quantity])
		formatString: #,0
		displayFolder: Sales Metrics
		lineageTag: 5e914420-dc4c-4a47-b376-6fd6ade30050

	measure 'Customer Rank' = ```
			
			IF( 
			    HASONEVALUE(Customers[Customer]), 
			    RANKX( 
			    ALLSELECTED(Customers), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: 2f823a25-58db-4640-bc89-c14c94552f4b

	measure 'Product Rank' = ```
			
			IF( 
			    HASONEVALUE(Products[Product]), 
			    RANKX( 
			    ALLSELECTED(Products), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: cc3f8a68-da6d-4f12-9b75-9d12af58fedf

	measure 'City Rank' = ```
			
			IF( 
			    HASONEVALUE(Customers[City]), 
			    RANKX( 
			    ALLSELECTED(Customers[City]), 
			    CALCULATE([Sales Revenue])
			    )
			)
			```
		formatString: 0
		displayFolder: Rank Metrics
		lineageTag: ec44490e-46ee-472a-9223-b165f7702334

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 1968f0f9-4bd9-4df3-a826-711c681aa5ff
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quantity
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 5582c0bb-734d-4b52-b246-0e791d11a5ff
		summarizeBy: sum
		sourceColumn: quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		isHidden
		sourceProviderType: decimal(38, 18)
		lineageTag: 1d12bb7b-d215-47a2-8af8-e817b7929a73
		summarizeBy: sum
		sourceColumn: sales_amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InvoiceId
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: c1b9353f-2129-41e1-a529-a0351350dc67
		summarizeBy: count
		sourceColumn: invoice_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductId
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: e39d59e4-ea8e-435d-81aa-42ffdd255138
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerId
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 7b5118d2-e978-452e-bb85-6b0f206a3676
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database(SqlDatabaseServer, SqlDatabaseName),
				    sales = Source{[Schema="gold",Item="sales"]}[Data]
				in
				    sales

	annotation PBI_ResultType = Table

	annotation IsTableInBiModel = True

