
name: Deploy with two workspace solution

on:
    workflow_dispatch:
      inputs:      
        project_name:
          description: Project Name
          required: true
          default: "Fubar"

jobs:
    deployment-job:
        name: Creating project [${{inputs.project_name}}]
        runs-on: ubuntu-latest
        permissions:
          contents: write
          repository-projects: write          
        steps:
            - name: Check out the code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6.2.0
              with:
                    python-version: "3.12"


            - name: Install azure-identity package
              run: |
                    pip install azure-identity -q

            - name: Install MSAL
              run: |
                    pip install msal -q

            - name: Install Python SDK for Fabric REST APIs
              run: |
                    pip install microsoft-fabric-api -q

            - name: fabric-cicd library
              run: |
                    pip install fabric-cicd -q

            - name: Install PyNaCl
              run: |
                    pip install PyNaCl -q

            - name: Deploy solution to new workspace      
              env:
                AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}    
                AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}                
                FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}             
                ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
                ADMIN_USER_UPN: ${{ secrets.ADMIN_USER_UPN }}
                DEVELOPERS_GROUP_ID: ${{ secrets.DEVELOPERS_GROUP_ID }}
                ADO_ORGANIZATION: ${{ secrets.ADO_ORGANIZATION }}
                ORGANIZATION_GITHUB: ${{ vars.ORGANIZATION_GITHUB }}
                PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
                PROJECT_NAME: ${{ inputs.project_name }}
              run:
                python src/deploy_with_two_workspace_solution.py