
name: Deploy Specialty Solution
run-name: Deploy ${{inputs.solution_name}}

on:
    workflow_dispatch:
        inputs:
            solution_name:
                type: choice
                description: Solution to deploy
                options: 
                - Custom Realtime Solution
                - NFL Players Stats Solution
                - NFL Data Agent Solution
                - SQL Database in Fabric Solution
                default: Custom Realtime Solution
            git_integration_provider:
                type: choice
                description: Git Integration Provider
                options: 
                - None
                - Azure DevOps
                - GitHub
                default: None
            run_as_service_principal:
                type: boolean
                description: Run as service principal
                default: true

jobs:
    deployment-job:
        name: Deploy ${{inputs.solution_name}}
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                    python-version: "3.12"

            - name: Install MSAL
              run: |
                    pip install msal -q

            - name: Install PyNaCl
              run: |
                    pip install PyNaCl -q

            - name: Install pyodbc
              run: |
                    pip install pyodbc -q

            - name: Install Microsoft ODBC
              run: sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y > /dev/null 2>&1

            - name: Deploy Solution                
              env:
                FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
                FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
                FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}                    
                FABRIC_CAPACITY_ID: ${{ secrets.FABRIC_CAPACITY_ID }}             
                ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
                SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
                PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
                SOLUTION_NAME: ${{inputs.solution_name}}
                GIT_INTEGRATION_PROVIDER: ${{inputs.git_integration_provider}}
                RUN_AS_SERVICE_PRINCIPAL: ${{inputs.run_as_service_principal}}
              run: 
                    python src/deploy_specialty_solution.py